VERSION 0.7
FROM alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
WORKDIR /quotes

artifact:
  COPY in.txt ./quotes.txt
  RUN echo Generated quotes:
  RUN cat quotes.txt
  SAVE ARTIFACT quotes.txt
